//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace AppFramework.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ValidationList))]
    public partial class DynEntityAttribValidation: IObjectWithChangeTracker, INotifyPropertyChanged, IDataEntity
    {
        #region Primitive Properties
    
        [DataMember]
        public long DynEntityAttribConfigId
        {
            get { return _dynEntityAttribConfigId; }
            set
            {
                if (_dynEntityAttribConfigId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'DynEntityAttribConfigId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _dynEntityAttribConfigId = value;
                    OnPropertyChanged("DynEntityAttribConfigId");
                }
            }
        }
        private long _dynEntityAttribConfigId;
    
        [DataMember]
        public long ValidationUid
        {
            get { return _validationUid; }
            set
            {
                if (_validationUid != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ValidationUid' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (ValidationList != null && ValidationList.ValidationUid != value)
                        {
                            ValidationList = null;
                        }
                    }
                    _validationUid = value;
                    OnPropertyChanged("ValidationUid");
                }
            }
        }
        private long _validationUid;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public ValidationList ValidationList
        {
            get { return _validationList; }
            set
            {
                if (!ReferenceEquals(_validationList, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (ValidationUid != value.ValidationUid)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _validationList;
                    _validationList = value;
                    FixupValidationList(previousValue);
                    OnNavigationPropertyChanged("ValidationList");
                }
            }
        }
        private ValidationList _validationList;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            ValidationList = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupValidationList(ValidationList previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.DynEntityAttribValidation.Contains(this))
            {
                previousValue.DynEntityAttribValidation.Remove(this);
            }
    
            if (ValidationList != null)
            {
                if (!ValidationList.DynEntityAttribValidation.Contains(this))
                {
                    ValidationList.DynEntityAttribValidation.Add(this);
                }
    
                ValidationUid = ValidationList.ValidationUid;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ValidationList")
                    && (ChangeTracker.OriginalValues["ValidationList"] == ValidationList))
                {
                    ChangeTracker.OriginalValues.Remove("ValidationList");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ValidationList", previousValue);
                }
                if (ValidationList != null && !ValidationList.ChangeTracker.ChangeTrackingEnabled)
                {
                    ValidationList.StartTracking();
                }
            }
        }

        #endregion

    }
}
