//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace AppFramework.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(InventoryScan))]
    public partial class InventoryScanItem: IObjectWithChangeTracker, INotifyPropertyChanged, IDataEntity
    {
        #region Primitive Properties
    
        [DataMember]
        public long Barcode
        {
            get { return _barcode; }
            set
            {
                if (_barcode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Barcode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _barcode = value;
                    OnPropertyChanged("Barcode");
                }
            }
        }
        private long _barcode;
    
        [DataMember]
        public long InventoryScanId
        {
            get { return _inventoryScanId; }
            set
            {
                if (_inventoryScanId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'InventoryScanId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (InventoryScan != null && InventoryScan.InventoryScanUid != value)
                        {
                            InventoryScan = null;
                        }
                    }
                    _inventoryScanId = value;
                    OnPropertyChanged("InventoryScanId");
                }
            }
        }
        private long _inventoryScanId;
    
        [DataMember]
        public long LocationId
        {
            get { return _locationId; }
            set
            {
                if (_locationId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'LocationId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _locationId = value;
                    OnPropertyChanged("LocationId");
                }
            }
        }
        private long _locationId;
    
        [DataMember]
        public int Count
        {
            get { return _count; }
            set
            {
                if (_count != value)
                {
                    _count = value;
                    OnPropertyChanged("Count");
                }
            }
        }
        private int _count;
    
        [DataMember]
        public string Comment
        {
            get { return _comment; }
            set
            {
                if (_comment != value)
                {
                    _comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        private string _comment;
    
        [DataMember]
        public System.DateTime ScanDate
        {
            get { return _scanDate; }
            set
            {
                if (_scanDate != value)
                {
                    _scanDate = value;
                    OnPropertyChanged("ScanDate");
                }
            }
        }
        private System.DateTime _scanDate;
    
        [DataMember]
        public System.DateTime UpdateDate
        {
            get { return _updateDate; }
            set
            {
                if (_updateDate != value)
                {
                    _updateDate = value;
                    OnPropertyChanged("UpdateDate");
                }
            }
        }
        private System.DateTime _updateDate;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public InventoryScan InventoryScan
        {
            get { return _inventoryScan; }
            set
            {
                if (!ReferenceEquals(_inventoryScan, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (InventoryScanId != value.InventoryScanUid)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _inventoryScan;
                    _inventoryScan = value;
                    FixupInventoryScan(previousValue);
                    OnNavigationPropertyChanged("InventoryScan");
                }
            }
        }
        private InventoryScan _inventoryScan;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            InventoryScan = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupInventoryScan(InventoryScan previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.InventoryScanItem.Contains(this))
            {
                previousValue.InventoryScanItem.Remove(this);
            }
    
            if (InventoryScan != null)
            {
                if (!InventoryScan.InventoryScanItem.Contains(this))
                {
                    InventoryScan.InventoryScanItem.Add(this);
                }
    
                InventoryScanId = InventoryScan.InventoryScanUid;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("InventoryScan")
                    && (ChangeTracker.OriginalValues["InventoryScan"] == InventoryScan))
                {
                    ChangeTracker.OriginalValues.Remove("InventoryScan");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("InventoryScan", previousValue);
                }
                if (InventoryScan != null && !InventoryScan.ChangeTracker.ChangeTrackingEnabled)
                {
                    InventoryScan.StartTracking();
                }
            }
        }

        #endregion

    }
}
