/****** Object:  Index [IX_Rigths_ViewId]    Script Date: 03/07/2012 18:20:42 ******/
CREATE NONCLUSTERED INDEX [IX_Rigths_ViewId] ON [dbo].[Rights] 
(
	[ViewId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


