ALTER TABLE [dbo].[AttributePanel]  WITH NOCHECK 
ADD  CONSTRAINT [FK_AttributePanel_ScreenId] 
FOREIGN KEY([ScreenId])
REFERENCES [dbo].[AssetTypeScreen] ([ScreenId])
ON DELETE CASCADE;

CREATE NONCLUSTERED INDEX [IX_AttributePanel_ScreenId] ON [dbo].[AttributePanel] 
(
	[ScreenId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO