//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsTaxonomies
    {
        public long DynEntityConfigUid { get; set; }
        public long DynEntityUid { get; set; }
        public string TaxonomyItemName { get; set; }
        public string TaxonomyName { get; set; }
        public long TaxonomyItemId { get; set; }
        public long TaxonomyItemUid { get; set; }
        public long TaxonomyUid { get; set; }
        public int TaxonomyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsCategory { get; set; }
        public string TaxonomyItemDescription { get; set; }
    }
}
