//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributePanelAttribute
    {
        public long AttributePanelUid { get; set; }
        public long DynEntityAttribConfigUId { get; set; }
        public int DisplayOrder { get; set; }
        public long UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public long AttributePanelAttributeId { get; set; }
        public Nullable<long> ReferencingDynEntityAttribConfigId { get; set; }
    
        public virtual AttributePanel AttributePanel { get; set; }
        public virtual DynEntityAttribConfig DynEntityAttribConfig { get; set; }
    }
}
