//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributePanel
    {
        public AttributePanel()
        {
            this.AttributePanelAttribute = new HashSet<AttributePanelAttribute>();
        }
    
        public long AttributePanelUid { get; set; }
        public long AttributePanelId { get; set; }
        public long DynEntityConfigUId { get; set; }
        public string Name { get; set; }
        public string NameTranslationId { get; set; }
        public byte DisplayOrder { get; set; }
        public string Description { get; set; }
        public string HeaderLabel { get; set; }
        public string HeaderLabelTranslationId { get; set; }
        public long UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<long> ScreenId { get; set; }
    
        public virtual DynEntityConfig DynEntityConfig { get; set; }
        public virtual AssetTypeScreen AssetTypeScreen { get; set; }
        public virtual ICollection<AttributePanelAttribute> AttributePanelAttribute { get; set; }
    }
}
