//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchSchedule
    {
        public long ScheduleId { get; set; }
        public Nullable<System.DateTime> LastStart { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime ExecuteAt { get; set; }
        public Nullable<double> RepeatInHours { get; set; }
        public string Notes { get; set; }
    }
}
