//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchJob
    {
        public BatchJob()
        {
            this.BatchActions = new HashSet<BatchAction>();
        }
    
        public long BatchUid { get; set; }
        public string Title { get; set; }
        public long OwnerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public short Status { get; set; }
        public bool SkipErrors { get; set; }
        public short ExecuteOn { get; set; }
        public Nullable<long> BatchScheduleId { get; set; }
    
        public virtual ICollection<BatchAction> BatchActions { get; set; }
        public virtual BatchSchedule BatchSchedule { get; set; }
    }
}
