//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynEntityAttribValidation
    {
        public long DynEntityAttribConfigId { get; set; }
        public long ValidationUid { get; set; }
    
        public virtual ValidationList ValidationList { get; set; }
    }
}
