//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryScan
    {
        public InventoryScan()
        {
            this.InventoryScanItem = new HashSet<InventoryScanItem>();
        }
    
        public long InventoryScanUid { get; set; }
        public long UserDynEntityId { get; set; }
        public bool OfflineScan { get; set; }
        public Nullable<System.DateTime> DateDataDownload { get; set; }
        public Nullable<System.DateTime> DateDataUpload { get; set; }
        public Nullable<System.DateTime> DateFirstScan { get; set; }
        public Nullable<System.DateTime> DateLastScan { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> NumberItemsScaned { get; set; }
        public Nullable<decimal> NumberFailed { get; set; }
        public long UserId { get; set; }
        public long UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<InventoryScanItem> InventoryScanItem { get; set; }
    }
}
