//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place2Zip
    {
        public long RelId { get; set; }
        public long PlaceId { get; set; }
        public long ZipId { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual ZipCode ZipCode { get; set; }
    }
}
