//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ReportField = new HashSet<ReportField>();
        }
    
        public long ReportUid { get; set; }
        public string Name { get; set; }
        public bool IsFinancial { get; set; }
        public string ReportFile { get; set; }
        public Nullable<long> DynConfigId { get; set; }
        public bool SyncWithOpenItem { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<ReportField> ReportField { get; set; }
    }
}
