//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public long ReservationUID { get; set; }
        public long DynEntityUID { get; set; }
        public long DynEntityConfigUID { get; set; }
        public long UpdateUserId { get; set; }
        public long Borrower { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDamaged { get; set; }
        public bool IsBorrowed { get; set; }
    }
}
