//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights
    {
        public long RightsUid { get; set; }
        public long ViewId { get; set; }
        public long UserId { get; set; }
        public long DynEntityConfigId { get; set; }
        public long CategoryId { get; set; }
        public long DepartmentId { get; set; }
        public byte Rights1 { get; set; }
        public bool IsDeny { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public long UpdateUserId { get; set; }
    }
}
