//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenLayout
    {
        public ScreenLayout()
        {
            this.AssetTypeScreen = new HashSet<AssetTypeScreen>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<AssetTypeScreen> AssetTypeScreen { get; set; }
    }
}
