//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchOperators
    {
        public SearchOperators()
        {
            this.DataType = new HashSet<DataType>();
        }
    
        public long SearchOperatorUid { get; set; }
        public string Operator { get; set; }
        public string ServiceMethod { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DataType> DataType { get; set; }
    }
}
