//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFramework.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.DynEntityTransactions = new HashSet<DynEntityTransaction>();
        }
    
        public long TransactionTypeUid { get; set; }
        public string Name { get; set; }
        public string NameTranslationId { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<DynEntityTransaction> DynEntityTransactions { get; set; }
    }
}
